name: Device farm tractor project build, test and publish results workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: ./gradlew build test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.26
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: build/test-results/**/*.xml
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test_results
        path: |
          build/reports/tests
          build/test-results
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.2.0
      if: always()
      with:
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build/reports/tests/test # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy
